#include "stdio.h" // standard IO header file

void main()
{
    int a = 10;
    int b = 20;
    float c = 20.0122;
    char my_char = 'a';
    char *my_char_ptr = "Hello";

    // print the values of the variables
    printf("The value of a is: %d\n", a);
    printf("The value of b is: %d\n", b);
    printf("The value of c is: %f\n", c);
    printf("The value of my_char is: %c\n", my_char);
    printf("The value of my_char_ptr is: %s\n", my_char_ptr);
}
